name: Create texlive cache

on:
  push:
    paths: 
      - .github/workflows/TEXLIVE_INIT_CACHE
    branches:
      - main

jobs:
  cache:
    runs-on: ubuntu-latest

    permissions: 
      contents: write
  
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: true
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install -r cgel/requirements.txt

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-full
